version: '3'
services:
  postgres:
    ports:
      - "127.0.0.1:35432:5432"
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oms_jira
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    ports:
      - "127.0.0.1:36379:6379"
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: