"""empty message

Revision ID: 2b2f4d1fe7ea
Revises: 6d2e561845c6
Create Date: 2021-07-13 21:57:32.845378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2f4d1fe7ea'
down_revision = '6d2e561845c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.add_column('project_item', sa.Column('project_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_item', 'project_id')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
