"""Initial

Revision ID: 6d2e561845c6
Revises: 
Create Date: 2021-07-01 23:10:45.476150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2e561845c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookkeeping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_event_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_event_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('jira_id', sa.Integer(), nullable=False),
    sa.Column('parent_type', sa.Enum('Project', 'ProjectItem', name='commenttype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_id'),
    sa.UniqueConstraint('mp_id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('jira_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_id'),
    sa.UniqueConstraint('mp_id')
    )
    op.create_table('project_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('jira_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_id'),
    sa.UniqueConstraint('mp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_item')
    op.drop_table('project')
    op.drop_table('comment')
    op.drop_table('bookkeeping')
    # ### end Alembic commands ###
