"""empty message

Revision ID: 81e0a4381b6c
Revises: 2b2f4d1fe7ea
Create Date: 2021-07-14 01:11:16.185851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e0a4381b6c'
down_revision = '2b2f4d1fe7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_mp_id_key', 'comment', type_='unique')
    op.drop_constraint('project_mp_id_key', 'project', type_='unique')
    op.drop_constraint('project_item_mp_id_key', 'project_item', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_item_mp_id_key', 'project_item', ['mp_id'])
    op.create_unique_constraint('project_mp_id_key', 'project', ['mp_id'])
    op.create_unique_constraint('comment_mp_id_key', 'comment', ['mp_id'])
    # ### end Alembic commands ###
